codefiesta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('workshops.urls')),
    path('', include('registration.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # TODO: Remove

eatsgood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', include('workshops.urls')),
    path('', include('registration.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon/favicon.ico'))),
    path('admin/', admin.site.urls),
]

registration/urls.py
from django.urls import path

from .views import log_in, sign_up, log_out, profile

app_name = 'registration'
urlpatterns = [
	path('login/', log_in, name='login'),
	path('signup/', sign_up, name='signup'),
	path('logout/', log_out, name='logout'),
	path('profile/<str:username>/', profile, name='profile'),
]

workshops/urls.py
from django.urls import path

from .views import index, workshop, workshop_signup, workshop_backout, workshop_upload

app_name = 'workshops'
urlpatterns = [
	path('', index, name='index'),
	path('workshops/<uuid:pk>/', workshop, name='workshop'),
	path('workshops/<uuid:pk>/signup', workshop_signup, name='workshop-signup'),
	path('workshops/<uuid:pk>/backout', workshop_backout, name='workshop-backout'),
	path('workshops/<uuid:pk>/upload', workshop_upload, name='workshop-upload'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>
	{% block head %}{% endblock %}
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	<link rel="stylesheet" href="{% static 'styles/index.min.css' %}">
	<link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
	<link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
	<link rel="mask-icon" href="{% static 'favicon/safari-pinned-tab.svg' %}" color="#fd7463">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="theme-color" content="#ffffff">
</head>
<body>
	{% block header %}{% include 'header.html' %}{% endblock %}
	{% block content %}{% endblock %}
</body>
</html>

templates/form.html
{% csrf_token %}
{% if form.non_field_errors %}
	<div class="form-error">
		{% for error in form.non_field_errors %}
			<p>
				<small>{{error}}</small>
			</p>
		{% endfor %}
	</div>
{% endif %}
{% for field in form.visible_fields %}
	<div class="field {% if field.field.required %}required{% endif %} {% if field.errors %}error{% endif %}">
		<strong>{{ field.label_tag }}</strong>
<!--		{% if field.help_text %}-->
<!--			<p>-->
<!--				<small class="form-help">{{ field.help_text }}</small>-->
<!--			</p>-->
<!--		{% endif %}-->
		{{ field }}
		{% if field.errors %}
			<div class="form-error">
				{% for error in field.errors %}
					<p>
						<small>{{error}}</small>
					</p>
				{% endfor %}
			</div>
		{% endif %}
		<div class="ui hidden divider"></div>
	</div>
{% endfor %}

templates/header-tagline.html
{% load static %}

<header>
	<div class="my-20">
		<nav class="navbar navbar-with-tagline">
			<div class="container-no-padding">
				<h1 class="nav-logo"><a href="{% url 'workshops:index' %}"><img src="{% static 'imgs/logo.svg' %}" alt="eatsgood"></a></h1>
				<h2 class="nav-tagline-desktop">Missing <span class="pink-red-text">Singapore</span>? Come join our cooking hangouts!</h2>
				<ul>
					{% if user.is_authenticated %}
						<li class="nav-link nav-link-pink-red"><a href="{% url 'registration:profile' username=user.username %}">My Profile</a></li>
						<li class="nav-link"><a href="{% url 'registration:logout' %}">Logout</a></li>
					{% else %}
						<li class="nav-link"><a href="{% url 'registration:signup' %}">Sign Up</a></li>
						<li class="nav-link"><a href="{% url 'registration:login' %}">Login</a></li>
					{% endif %}
				</ul>
			</div>
		</nav>
		<div class="container-no-padding">
			<p class="nav-tagline-mobile">Missing <span class="pink-red-text">Singapore</span>? Come join our cooking hangouts!</p>
		</div>
	</div>
</header>

templates/header.html
{% load static %}

<header>
	<div class="mobile-header my-20">
		<nav class="navbar">
			<div class="container-no-padding">
				<h1 class="nav-logo"><a href="{% url 'workshops:index' %}"><img src="{% static 'imgs/logo.svg' %}"></a></h1>
				<ul>
					{% if user.is_authenticated %}
						<li class="nav-link nav-link-pink-red"><a href="{% url 'registration:profile' username=user.username %}">Your Profile</a></li>
						<li class="nav-link"><a href="{% url 'registration:logout' %}">Logout</a></li>
					{% else %}
						<li class="nav-link"><a href="{% url 'registration:signup' %}">Sign Up</a></li>
						<li class="nav-link"><a href="{% url 'registration:login' %}">Login</a></li>
					{% endif %}
				</ul>
			</div>
		</nav>
		<div class="container-no-padding">
			<p class="header-tagline">Missing <span class="dark-red-text">Singapore</span>? Come join our cooking hangouts!</p>
		</div>
	</div>
	<div class="desktop-header my-20">
		<nav class="navbar">
			<div class="container-no-padding">
				<h1 class="nav-logo"><a href="{% url 'workshops:index' %}"><img src="{% static 'imgs/logo.svg' %}"></a></h1>
				<h2 class="header-tagline">Missing <span class="dark-red-text">Singapore</span>? Come join our cooking hangouts!</h2>
				<ul>
					{% if user.is_authenticated %}
						<li class="nav-link nav-link-pink-red"><a href="{% url 'registration:profile' username=user.username %}">Your Profile</a></li>
						<li class="nav-link"><a href="{% url 'registration:logout' %}">Logout</a></li>
					{% else %}
						<li class="nav-link"><a href="{% url 'registration:signup' %}">Sign Up</a></li>
						<li class="nav-link"><a href="{% url 'registration:login' %}">Login</a></li>
					{% endif %}
				</ul>
			</div>
		</nav>
	</div>
</header>