codefiesta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('workshops.urls')),
    path('', include('registration.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # TODO: Remove

eatsgood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', include('workshops.urls')),
    path('', include('registration.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon/favicon.ico'))),
    path('admin/', admin.site.urls),
]

registration/urls.py
from django.urls import path

from .views import log_in, sign_up, log_out, profile

app_name = 'registration'
urlpatterns = [
	path('login/', log_in, name='login'),
	path('signup/', sign_up, name='signup'),
	path('logout/', log_out, name='logout'),
	path('profile/<str:username>/', profile, name='profile'),
]

workshops/urls.py
from django.urls import path

from .views import index, workshop, workshop_signup, workshop_backout, workshop_upload

app_name = 'workshops'
urlpatterns = [
	path('', index, name='index'),
	path('workshops/<uuid:pk>/', workshop, name='workshop'),
	path('workshops/<uuid:pk>/signup', workshop_signup, name='workshop-signup'),
	path('workshops/<uuid:pk>/backout', workshop_backout, name='workshop-backout'),
	path('workshops/<uuid:pk>/upload', workshop_upload, name='workshop-upload'),
]

workshops/models.py
import uuid
import datetime
from django.utils import timezone
from django.conf import settings
from django.db import models
from timezone_field import TimeZoneField
from django_countries.fields import CountryField


class Tag(models.Model):
	name = models.SlugField(
		help_text='Name of the tag.',
		max_length=200,
		unique=True,
	)

	def __str__(self):
		return self.name


class Workshop(models.Model):
	id = models.UUIDField(
		help_text='Unique identifier',
		primary_key=True,
		default=uuid.uuid4,
		editable=False,
	)

	author = models.ForeignKey(
		help_text='The user this workshop is created by.',
		to=settings.AUTH_USER_MODEL,
		related_name='created_workshops',
		on_delete=models.CASCADE,
	)

	title = models.CharField(
		help_text='Title of the workshop.',
		max_length=200,
	)

	start_datetime = models.DateTimeField(
		help_text='When this workshop will take place.',
	)

	duration = models.DurationField(
		help_text='How long the workshop will be.',
	)

	zoom_link = models.CharField(
		help_text='Zoom link to the workshop.',
		blank=True,
		max_length=200,
	)

	zoom_passcode = models.CharField(
		help_text='Zoom passcode to the workshop.',
		blank=True,
		max_length=200,
	)

	tags = models.ManyToManyField(
		help_text='The tags that the workshop is related to.',
		to=Tag,
		related_name='workshops',
	)

	cover_photo = models.ImageField(
		help_text='The cover photo of the workshop.',
		upload_to='workshop_cover_photos',
		max_length=200,
	)

	description = models.TextField(
		help_text='Description of the workshop.',
	)

	ingredients = models.TextField(
		help_text='Ingredients needed for the workshop.',
	)

	equipment = models.TextField(
		help_text='Equipment needed for the workshop.',
	)

	created_at = models.DateTimeField(
		help_text='When the workshop is created.',
		auto_now_add=True,
	)

	attendees = models.ManyToManyField(
		to=settings.AUTH_USER_MODEL,
		related_name='registered_workshops',
		blank=True,
	)

	country = CountryField(
		help_text='The country you live in.',
	)

	timezone = TimeZoneField(
		help_text='The timezone to use as reference.',
		default='Asia/Singapore',
	)

	@property
	def is_open_for_registration(self):
		return (self.start_datetime + datetime.timedelta(hours=24)) >= timezone.now()

	@property
	def is_past_workshop(self):
		return timezone.now() >= self.start_datetime

	@property
	def formatted_datetime(self):
		local_start_datetime = self.start_datetime.astimezone(tz=self.timezone)
		local_end_datetime = (self.start_datetime + self.duration).astimezone(tz=self.timezone)
		if local_start_datetime.strftime("%a, %b %-d") == local_end_datetime.strftime("%a, %b %-d"):
			if local_start_datetime.strftime("%p") == local_end_datetime.strftime("%p"):
				return local_start_datetime.strftime("%a, %b %-d · %-I:%M") + local_end_datetime.strftime(" - %-I:%M %p %Z")
			else:
				return local_start_datetime.strftime("%a, %b %-d · %-I:%M %p") + local_end_datetime.strftime(
					" - %-I:%M %p %Z")
		else:
			return local_start_datetime.strftime("%a, %b %-d · %-I:%M %p") + local_end_datetime.strftime(
				" - %a, %b %-d · %-I:%M %p %Z")

	def __str__(self):
		return self.title

	class Meta:
		ordering = ('start_datetime',)


class WorkshopPhoto(models.Model):
	workshop = models.ForeignKey(
		help_text='The workshop that this photo is for.',
		to=Workshop,
		on_delete=models.CASCADE,
		related_name='workshop_photos',
	)

	author = models.ForeignKey(
		help_text='The user this photo belongs to.',
		to=settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
		related_name='workshop_photos',
	)
	
	photo = models.ImageField(
		help_text='The photo taken by the user during the workshop.',
		upload_to='workshop_photos',
		max_length=200,
	)

	description = models.TextField(
		help_text='Description of the photo.',
	)

	created_at = models.DateTimeField(
		help_text='When the photo is created.',
		auto_now_add=True,
	)

	def __str__(self):
		return self.description

	class Meta:
		ordering = ('-created_at',)


class WorkshopPost(models.Model):
	id = models.UUIDField(
		help_text='Unique identifier',
		primary_key=True,
		default=uuid.uuid4,
		editable=False,
	)

	workshop = models.ForeignKey(
		help_text='Which workshop is this post related to',
		to=Workshop,
		on_delete=models.CASCADE,
		related_name='posts',
	)

	author = models.ForeignKey(
		help_text='The user this post belongs to.',
		to=settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
		related_name='posts',
	)

	title = models.CharField(
		help_text='Title of the post.',
		max_length=200,
	)

	content = models.TextField(
		help_text='Content of the post.',
	)

	likes = models.ManyToManyField(
		help_text='Users who like this post.',
		to=settings.AUTH_USER_MODEL,
		related_name='posts_liked',
		blank=True,
	)

	created_at = models.DateTimeField(
		help_text='When the post is created.',
		auto_now_add=True,
	)

	def __str__(self):
		return self.title

	class Meta:
		ordering = ('-created_at',)


class WorkshopComment(models.Model):
	id = models.UUIDField(
		help_text='Unique identifier',
		primary_key=True,
		default=uuid.uuid4,
		editable=False,
	)

	author = models.ForeignKey(
		help_text='The user this comment belongs to.',
		to=settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
		related_name='comments',
	)

	post = models.ForeignKey(
		WorkshopPost,
		on_delete=models.CASCADE,
		related_name='comments',
	)

	content = models.TextField(
		help_text='Content of the comment.',
	)

	likes = models.ManyToManyField(
		help_text='Users who like this comment.',
		to=settings.AUTH_USER_MODEL,
		related_name='comments_liked',
		blank=True,
	)

	created_at = models.DateTimeField(
		help_text='When the comment is created.',
		auto_now_add=True,
	)

	def __str__(self):
		return self.content

	class Meta:
		ordering = ('-created_at',)

workshops/forms.py
from django.forms import ModelForm

from .models import WorkshopPhoto

class WorkshopPhotoForm(ModelForm):
    class Meta:
        model = WorkshopPhoto
        fields = ['photo', 'description']

workshops/views.py
from django.views.decorators.http import require_http_methods
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django_countries import countries

from .forms import WorkshopPhotoForm
from .models import Workshop, WorkshopPhoto

@require_http_methods(['GET'])
def index(request):
	context = {
		'countries': countries,
		'workshops': [workshop for workshop in Workshop.objects.all() if workshop.is_open_for_registration],
		'workshop_photos': WorkshopPhoto.objects.all(),
	}

	return render(request, 'workshops/index.html', context)

@require_http_methods(['GET'])
def workshop(request, pk):
	did_upload = False
	workshop = get_object_or_404(Workshop, pk=pk)

	if request.user.is_authenticated:
		did_upload = WorkshopPhoto.objects.filter(author=request.user, workshop=workshop).count() > 0

	context = {
		"workshop": get_object_or_404(Workshop, pk=pk),
		"did_upload": did_upload,
	}

	return render(request, 'workshops/workshop.html', context)

@require_http_methods(['POST'])
def workshop_signup(request, pk):
	if not request.user.is_authenticated:
		return HttpResponseRedirect(reverse('registration:login') + "?next=" + reverse('workshops:workshop', kwargs={'pk':pk}))

	workshop = get_object_or_404(Workshop, pk=pk)
	workshop.attendees.add(request.user)

	context = {
		"workshop": workshop
	}

	return render(request, 'workshops/workshop_signup.html', context)

@require_http_methods(['GET', 'POST'])
def workshop_backout(request, pk):
	if not request.user.is_authenticated:
		raise Http404

	workshop = get_object_or_404(Workshop, pk=pk)
	context = {
		"workshop": workshop,
	}

	if request.method == 'POST':
		workshop.attendees.remove(request.user)
		return render(request, 'workshops/workshop_backout_success.html', context)

	else:
		return render(request, 'workshops/workshop_backout_confirmation.html', context)

@require_http_methods(['GET', 'POST'])
def workshop_upload(request, pk):
	workshop = get_object_or_404(Workshop, pk=pk)

	if request.method == 'POST':
		workshop_photo = WorkshopPhoto(author=request.user, workshop=workshop)
		form = WorkshopPhotoForm(data=request.POST, files=request.FILES, instance=workshop_photo)

		if form.is_valid():
			form.save()
			return redirect('registration:profile', username=request.user.username)

	else:
		form = WorkshopPhotoForm()

	context = {
		"workshop": workshop,
		"form": form,
	}

	return render(request, 'workshops/workshop_photo_form.html', context)

workshops/templates/workshops/gallery_photo.html
<a class="gallery-photo-link" href="{% url 'registration:profile' username=workshop_photo.author.username %}">
	<div class="gallery-photo-div">
		<img src="{{workshop_photo.photo.url}}" alt="{{workshop_photo.description}}" />
	</div>
</a>

workshops/templates/workshops/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}eatsgood{% endblock %}

{% block header %}{% include 'header-tagline.html' %}{% endblock %}

{% block content %}

<section>
	<div class="img-bg-wrapper jumbotron-img-bg">
		<img class="img-bg img-bg-mobile" src="{% static 'imgs/mobile-jumbotron.png' %}" />
		<img class="img-bg img-bg-desktop" src="{% static 'imgs/desktop-jumbotron.png' %}" />
		<form method="GET" class="jumbotron-content container">
			<div class="jumbotron-location">
				<label for="location">Location</label>
				<select id="location" name="location">
					<option value="" selected disabled>Select a country</option>
					{% for country in countries %}
						<option value="{{country.0}}">{{country.1}}</option>
					{% endfor %}
				</select>
			</div>
			<div class="jumbotron-search">
				<img src="{% static 'imgs/search.svg' %}" alt="search-icon" />
				<input name="search-value" placeholder="Search for food you want to make">
			</div>
		</form>
	</div>
</section>
<section>
	<div class="container">
		<div class="workshop-list-header">
			<h2>Join Upcoming Cookouts</h2>
			<a href="">View All</a>
		</div>
		{% if workshops|length > 0 %}
			<div class="grid">
				{% for workshop in workshops %}
					{% include 'workshops/workshop_card.html' %}
				{% endfor %}
			</div>
		{% else %}
			<p class="mid-grey-text">Sorry, there's no upcoming cookouts right now</p>
		{% endif %}
	</div>
</section>
<section>
	<div class="container">
		<h2>Cooked by fellow Singaporeans</h2>
		{% if workshop_photos|length > 0 %}
			<div class="grid gallery-photos">
				{% for workshop_photo in workshop_photos %}
					{% include 'workshops/gallery_photo.html' %}
				{% endfor %}
			</div>
		{% else %}
			<p class="mid-grey-text">Sorry, there's no workshop photos available yet</p>
		{% endif %}
	</div>
</section>
<footer>
	<div class="img-bg-wrapper footer-img-bg">
		<img class="img-bg img-bg-mobile" src="{% static 'imgs/mobile-footer.png' %}" />
		<img class="img-bg img-bg-desktop" src="{% static 'imgs/desktop-footer.png' %}" />
		<div class="container">
			<p class="center footer-text">
				Nothing brings people together<br>
				like good food
			</p>
		</div>
	</div>
</footer>

{% endblock %}

workshops/templates/workshops/workshop.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{workshop.title}}{% endblock %}

{% block content %}

<section>
	<div class="container pt-0">
		<div class="workshop-header">
			<p>Join this cookout and make</p>
			<h2>{{workshop.title}}</h2>
			<div class="workshop-header-img">
				<img src="{{workshop.cover_photo.url}}" />
			</div>
		</div>
	</div>
</section>
<section class="workshop-detail-wrapper">
	<div class="container">
		<div class="workshop-datetime">
			<img src="{% static 'imgs/clock.svg' %}" alt="clock icon" />
			<p>{{workshop.formatted_datetime}}</p>
		</div>
		{% if workshop.is_past_workshop %}
			<p class="pink-red-text"><strong>Event Passed</strong></p>
		{% endif %}
		<div>
			<div class="workshop-detail">
				<p><strong>Description:</strong></p>
				<p>{{workshop.description}}</p>
			</div>
			{% if user in workshop.attendees.all and workshop.zoom_link %}
				<div class="workshop-detail">
					<p><strong>Zoom Link:</strong></p>
					<p><a class="link" href="{{workshop.zoom_link}}">{{workshop.zoom_link}}</a>{% if workshop.zoom_passcode %}<br>(Passcode: {{workshop.zoom_passcode}}){% endif %}</p>
				</div>
			{% endif %}
			<p><strong>Location:</strong> {{workshop.description}}</p>
			<p><strong>Tags:</strong> {% for tag in workshop.tags.all %}#{{tag.name}} {% endfor %}</p>
		</div>
		<div class="collapsible">
			<input type="checkbox" class="collapsible-checkbox" id="ingredients-needed-checkbox">
			<div class="collapsible-header">
				<h3><strong>Ingredients Needed:</strong></h3>
				<label for="ingredients-needed-checkbox"><img src="{% static 'imgs/chevron-up.svg' %}" /></label>
			</div>
			<div class="collapsible-content">
				<p>{{workshop.ingredients|linebreaks}}</p>
			</div>
		</div>
		<div class="collapsible">
			<input type="checkbox" class="collapsible-checkbox" id="equipment-needed-checkbox">
			<div class="collapsible-header">
				<h3><strong>Equipment Needed:</strong></h3>
				<label for="equipment-needed-checkbox"><img src="{% static 'imgs/chevron-up.svg' %}" /></label>
			</div>
			<div class="collapsible-content">
				<p>{{workshop.equipment|linebreaks}}</p>
			</div>
		</div>
		<div class="collapsible">
			<input type="checkbox" class="collapsible-checkbox" id="forum-checkbox">
			<div class="collapsible-header">
				<h3><strong>Forum:</strong></h3>
				<label for="forum-checkbox"><img src="{% static 'imgs/chevron-up.svg' %}" /></label>
			</div>
			<div class="collapsible-content">
				<img class="mt-20" src="{% static 'imgs/blog-sample.png' %}" style="width: 100%;" />
			</div>
		</div>
	</div>
</section>
<section class="workshop-fixed">
	<div class="container-no-padding">
		<div class="workshop-attendees">
			<img src="{% static 'imgs/smile.svg' %}" />
			{% if user in workshop.attendees.all %}
				<p>You and {{workshop.attendees.count|add:-1}} attendee{% if workshop.attendees.count != 2 %}s{% endif %}</p>
			{% else %}
				<p>{{workshop.attendees.count}} attendee{% if workshop.attendees.count != 1 %}s{% endif %}</p>
			{% endif %}
		</div>
		{% if workshop.is_past_workshop %}
			{% if user in workshop.attendees.all %}
				{% if did_upload %}
					<a href="{% url 'workshops:workshop-upload' pk=workshop.pk %}" class="btn btn-darker-grey">Uploaded</a>
				{% else %}
					<a href="{% url 'workshops:workshop-upload' pk=workshop.pk %}" class="btn btn-blue">Upload</a>
				{% endif %}
			{% endif %}
		{% else %}
			{% if user in workshop.attendees.all %}
				<a href="{% url 'workshops:workshop-backout' pk=workshop.pk %}" class="btn btn-darker-grey">Backout</a>
			{% else %}
				<form method="POST" action="{% url 'workshops:workshop-signup' pk=workshop.pk %}">
					{% csrf_token %}
					<button type="submit" class="btn">Sign Up</button>
				</form>
			{% endif %}
		{% endif %}
	</div>
</section>
<section class="workshop-spacing">
</section>

{% endblock %}

workshops/templates/workshops/workshop_backout_confirmation.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{workshop.title}} | Backout Confirmation{% endblock %}

{% block content %}

<section>
	<div class="container pt-0">
		<h2>Do you want to backout of this cookout?</h2>
		<div class="flex">
			<form method="POST" action="{% url 'workshops:workshop-backout' pk=workshop.pk %}" class="mr-10">
				{% csrf_token %}
				<button type="submit" class="btn btn-white-outline">Yes</button>
			</form>
			<a class="btn btn-darker-grey" href="{% url 'workshops:workshop' pk=workshop.pk %}">No</a>
		</div>
	</div>
</section>

{% endblock %}

workshops/templates/workshops/workshop_backout_success.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{workshop.title}} | Backout Successful{% endblock %}

{% block content %}

<section>
	<div class="container pt-0">
		<div class="mb-30">
			<h2>Backout Successful</h2>
			<p>We're sad to see you go.</p>
			<p>:(</p>
		</div>
		<a class="btn" href="{% url 'workshops:workshop' pk=workshop.pk %}">Back to cookout page</a>
	</div>
</section>

{% endblock %}

workshops/templates/workshops/workshop_card.html
<a href="{% url 'workshops:workshop' pk=workshop.pk %}" class="workshop-card-link">
	<div class="workshop-card">
		<img class="workshop-card-img" src="{{workshop.cover_photo.url}}" />
		<div class="workshop-card-content">
			<p class="small-text">{{workshop.formatted_datetime}}</p>
			<h3><strong>{{workshop.title}}</strong></h3>
			<p class="workshop-card-tags">
				{% for tag in workshop.tags.all %}
					#{{tag.name}}
				{% endfor %}
			</p>
			<p class="workshop-card-country"><strong>{{workshop.country.name}}</strong></p>
			<p class="workshop-card-attendees">{{workshop.attendees.count}} attendee{% if workshop.attendees.count != 1 %}s{% endif %}</p>
		</div>
	</div>
</a>

workshops/templates/workshops/workshop_photo_form.html
{% extends "base.html" %}

{% block title %}{{workshop.title}} | Photo Upload{% endblock %}

{% block content %}

<section>
	<div class="container pt-0">
		<div class="workshop-header">
			<p>Keep a memory of your cookout</p>
			<div class="workshop-header-img">
				<img id="workshop-photo" src="{{workshop.cover_photo.url}}" />
			</div>
		</div>
	</div>
</section>
<section>
	<form method="post" class="form-group" enctype="multipart/form-data">
		<div class="container">
			{% include "form.html" %}
		</div>
		<div class="workshop-fixed">
			<div class="container-no-padding">
				<div></div>
				<div>
					<a href="{% url 'workshops:workshop' pk=workshop.pk %}" class="btn btn-blue-outline mr-10">Cancel</a>
					<button class="btn btn-blue" type="submit">Upload</button>
				</div>
			</div>
		</div>
	</form>
</section>
<section class="workshop-spacing">
</section>
<script>
	window.onload = function() {
		function readURL(input) {
			if (input.target.files && input.target.files[0]) {
				var reader = new FileReader();

				reader.onload = function (e) {
					let img = document.getElementById('workshop-photo');
					img.setAttribute("src", e.target.result);
				};

				reader.readAsDataURL(input.target.files[0]);
			}
		}
		document.getElementById('id_photo').addEventListener('change', readURL);
    }
</script>

{% endblock %}

workshops/templates/workshops/workshop_signup.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{workshop.title}} | Sign Up Successful{% endblock %}

{% block content %}

<section>
	<div class="container pt-0">
		<div class="mb-30">
			<h2>Sign Up Successful!</h2>
			<p>See you at the cookout!</p>
			<p>(^0^)/</p>
		</div>
		<a class="btn" href="{% url 'workshops:workshop' pk=workshop.pk %}">Back to cookout page</a>
	</div>
</section>

{% endblock %}